
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8S Terraform azure!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  displayName: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformCLI@2
  displayName: 'terraform-init'
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    backendAzureRmSubscriptionId: '4866ad87-d4e3-41de-a499-2d9ed0600532'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'uksouth'
    backendAzureRmStorageAccountName: 'storageaccountsattia'
    backendAzureRmContainerName: 'storageaccountsattiacontainer'
    backendAzureRmKey: 'kuberentes-dev.tfstate'
    allowTelemetryCollection: true

- task: TerraformCLI@2
  displayName: 'terraform-apply'
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'azure-resource-manager-service-connection'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    allowTelemetryCollection: true
